const express=require('express');
const {Client,GatewayIntentBits,REST,Routes,SlashCommandBuilder,EmbedBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle,ModalBuilder,TextInputBuilder,TextInputStyle,MessageFlags}=require('discord.js');
const app=express(); const PORT=process.env.PORT||10000; app.get('/',(_,res)=>res.send('BOOYAH HUB bot is running.')); app.listen(PORT,'0.0.0.0');
const token=process.env.DISCORD_TOKEN; if(!token){console.error('Missing DISCORD_TOKEN');process.exit(1)}
const client=new Client({intents:[GatewayIntentBits.Guilds]}); const registrations=new Map();
const commands=[new SlashCommandBuilder().setName('setup-registration').setDescription('Post the BOOYAH Hub team registration panel'),new SlashCommandBuilder().setName('registration').setDescription('Show current team registrations'),new SlashCommandBuilder().setName('reset-registration').setDescription('Reset all current registrations')].map(c=>c.toJSON());
client.once('ready',async()=>{console.log(`Logged in as ${client.user.tag}`);const rest=new REST({version:'10'}).setToken(token);try{await rest.put(Routes.applicationCommands(client.user.id),{body:commands});console.log('Slash commands registered.')}catch(e){console.error(e)}});
function isOpen(){const p=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Kolkata',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date());const h=+p.find(x=>x.type==='hour').value,m=+p.find(x=>x.type==='minute').value,n=h*60+m;return n>=1080&&n<1260}
function list(){if(!registrations.size)return 'No teams registered yet.';return [...registrations].map(([s,r])=>`**Slot ${s} — ${r.team}**\nCaptain: ${r.captain}\nPlayers: ${r.players.join(', ')}\nSubstitute: ${r.substitute}`).join('\n\n')}
client.on('interactionCreate',async i=>{try{
if(i.isChatInputCommand()){if(i.commandName==='setup-registration'){const e=new EmbedBuilder().setTitle('🔥 BOOYAH HUB DAILY SCRIM').setDescription('Registration is open from **6:00 PM to 9:00 PM IST**.\nMaximum **12 teams**.\n\nClick **Register Team** to enter.');const row=new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('register_team').setLabel('Register Team').setStyle(ButtonStyle.Primary));return i.reply({embeds:[e],components:[row]})}if(i.commandName==='registration')return i.reply({content:list(),flags:MessageFlags.Ephemeral});if(i.commandName==='reset-registration'){registrations.clear();return i.reply({content:'✅ Registration has been reset.',flags:MessageFlags.Ephemeral})}}
if(i.isButton()&&i.customId==='register_team'){if(!isOpen())return i.reply({content:'⛔ Registration is closed. Open: 6:00 PM–9:00 PM IST.',flags:MessageFlags.Ephemeral});if(registrations.size>=12)return i.reply({content:'⛔ All 12 slots are full.',flags:MessageFlags.Ephemeral});const m=new ModalBuilder().setCustomId('team_registration_modal').setTitle('BOOYAH HUB Team Registration');const f=(id,label,style=TextInputStyle.Short)=>new TextInputBuilder().setCustomId(id).setLabel(label).setStyle(style).setRequired(true);m.addComponents(new ActionRowBuilder().addComponents(f('team','Team name')),new ActionRowBuilder().addComponents(f('captain','Captain')),new ActionRowBuilder().addComponents(f('players','4 main players (one per line)',TextInputStyle.Paragraph)),new ActionRowBuilder().addComponents(f('substitute','Substitute')));return i.showModal(m)}
if(i.isModalSubmit()&&i.customId==='team_registration_modal'){if(!isOpen())return i.reply({content:'⛔ Registration is closed.',flags:MessageFlags.Ephemeral});if(registrations.size>=12)return i.reply({content:'⛔ All 12 slots are full.',flags:MessageFlags.Ephemeral});const team=i.fields.getTextInputValue('team').trim(),captain=i.fields.getTextInputValue('captain').trim(),players=i.fields.getTextInputValue('players').split(/\n|,/).map(x=>x.trim()).filter(Boolean),substitute=i.fields.getTextInputValue('substitute').trim();if(players.length!==4)return i.reply({content:'❌ Enter exactly 4 main players, one per line.',flags:MessageFlags.Ephemeral});if(!players.map(x=>x.toLowerCase()).includes(captain.toLowerCase()))return i.reply({content:'❌ Captain must be one of the 4 main players.',flags:MessageFlags.Ephemeral});if([...registrations.values()].some(r=>r.team.toLowerCase()===team.toLowerCase()))return i.reply({content:'❌ That team name is already registered.',flags:MessageFlags.Ephemeral});const slot=registrations.size+1;registrations.set(slot,{team,captain,players,substitute});return i.reply({content:`✅ **${team}** registered successfully as **Slot ${slot}**.`,flags:MessageFlags.Ephemeral})}}catch(e){console.error('Interaction error:',e);if(!i.replied&&!i.deferred)await i.reply({content:'⚠️ Something went wrong. Please try again.',flags:MessageFlags.Ephemeral}).catch(()=>{})}});
client.login(token).catch(e=>{console.error(e);process.exit(1)});
